spring:
  datasource:
    url: jdbc:mysql://120.78.206.78:3306/psds-advanced?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root123..
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /psds
  port: 8080

